In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install matplotlib

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data=pd.read_excel('/content/iris (1).xls')

In [6]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [7]:
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
from sklearn.preprocessing import LabelEncoder
el= LabelEncoder()
data['Classification']=el.fit_transform(data['Classification'])

In [11]:
data.head()

SL   SW   PL   PW  Classification
0  5.1  3.5  1.4  0.2               0
1  4.9  3.0  1.4  0.2               0
2  4.7  3.2  1.3  0.2               0
3  4.6  3.1  1.5  0.2               0
4  5.0  3.6  1.4  0.2               0

In [13]:
x=data.drop(['Classification'],axis=1)
y=data['Classification']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

###Radial Basis Function

In [17]:
from sklearn.svm import SVC
sv_cls=SVC(kernel='rbf')
sv_cls=sv_cls.fit(x_train,y_train)

In [18]:
y_pred_svm=sv_cls.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score

In [20]:
confusion_matrix(y_test,y_pred_svm)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [21]:
accuracy_score(y_test,y_pred_svm)

1.0

In [24]:
precision_score(y_test,y_pred_svm,average='micro')

1.0

###Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier

dt1_cls=DecisionTreeClassifier()
dt1_cls=dt1_cls.fit(x_train,y_train)
y_pred_dt1=dt1_cls.predict(x_test)

In [26]:
confusion_matrix(y_test,y_pred_dt1)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [27]:
accuracy_score(y_test,y_pred_dt1)

1.0

In [28]:
precision_score(y_test,y_pred_dt1,average='micro')

1.0

###Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier
rd1_cls= RandomForestClassifier()
rd1_cls=rd1_cls.fit(x_train,y_train)
y_pred_rd1=rd1_cls.predict(x_test)

In [30]:
confusion_matrix(y_test,y_pred_rd1)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [31]:
accuracy_score(y_test,y_pred_rd1)

1.0

In [32]:
precision_score(y_test,y_pred_rd1,average='micro')

1.0

###Linear Regression

In [33]:
sv_cls=SVC(kernel='linear')
sv_cls=sv_cls.fit(x_train,y_train)

In [34]:
y_pred_svm=sv_cls.predict(x_test)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score

In [36]:
confusion_matrix(y_test,y_pred_svm)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [37]:
accuracy_score(y_test,y_pred_svm)

1.0

In [38]:
precision_score(y_test,y_pred_svm,average='micro')

1.0